// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetFeeVotesFeevoteProducerParams creates a new GetFeeVotesFeevoteProducerParams object
//
// There are no default values defined in the spec.
func NewGetFeeVotesFeevoteProducerParams() GetFeeVotesFeevoteProducerParams {

	return GetFeeVotesFeevoteProducerParams{}
}

// GetFeeVotesFeevoteProducerParams contains all the bound params for the get fee votes feevote producer operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetFeeVotesFeevoteProducer
type GetFeeVotesFeevoteProducerParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The producer's account
	  Required: true
	  In: path
	*/
	Producer string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetFeeVotesFeevoteProducerParams() beforehand.
func (o *GetFeeVotesFeevoteProducerParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rProducer, rhkProducer, _ := route.Params.GetOK("producer")
	if err := o.bindProducer(rProducer, rhkProducer, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindProducer binds and validates parameter Producer from path.
func (o *GetFeeVotesFeevoteProducerParams) bindProducer(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Producer = raw

	return nil
}
