// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFeeVotesProducerUsdHandlerFunc turns a function with the right signature into a get fee votes producer usd handler
type GetFeeVotesProducerUsdHandlerFunc func(GetFeeVotesProducerUsdParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFeeVotesProducerUsdHandlerFunc) Handle(params GetFeeVotesProducerUsdParams) middleware.Responder {
	return fn(params)
}

// GetFeeVotesProducerUsdHandler interface for that can handle valid get fee votes producer usd params
type GetFeeVotesProducerUsdHandler interface {
	Handle(GetFeeVotesProducerUsdParams) middleware.Responder
}

// NewGetFeeVotesProducerUsd creates a new http.Handler for the get fee votes producer usd operation
func NewGetFeeVotesProducerUsd(ctx *middleware.Context, handler GetFeeVotesProducerUsdHandler) *GetFeeVotesProducerUsd {
	return &GetFeeVotesProducerUsd{Context: ctx, Handler: handler}
}

/* GetFeeVotesProducerUsd swagger:route GET /fee/votes/{producer}/usd getFeeVotesProducerUsd

list a producer's fee vote in USD as a float

*/
type GetFeeVotesProducerUsd struct {
	Context *middleware.Context
	Handler GetFeeVotesProducerUsdHandler
}

func (o *GetFeeVotesProducerUsd) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFeeVotesProducerUsdParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
