// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFeeVotesProducerHandlerFunc turns a function with the right signature into a get fee votes producer handler
type GetFeeVotesProducerHandlerFunc func(GetFeeVotesProducerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFeeVotesProducerHandlerFunc) Handle(params GetFeeVotesProducerParams) middleware.Responder {
	return fn(params)
}

// GetFeeVotesProducerHandler interface for that can handle valid get fee votes producer params
type GetFeeVotesProducerHandler interface {
	Handle(GetFeeVotesProducerParams) middleware.Responder
}

// NewGetFeeVotesProducer creates a new http.Handler for the get fee votes producer operation
func NewGetFeeVotesProducer(ctx *middleware.Context, handler GetFeeVotesProducerHandler) *GetFeeVotesProducer {
	return &GetFeeVotesProducer{Context: ctx, Handler: handler}
}

/* GetFeeVotesProducer swagger:route GET /fee/votes/{producer} getFeeVotesProducer

list a producer's fee vote in whole FIO as a float

*/
type GetFeeVotesProducer struct {
	Context *middleware.Context
	Handler GetFeeVotesProducerHandler
}

func (o *GetFeeVotesProducer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFeeVotesProducerParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
