// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFeeHandlerFunc turns a function with the right signature into a get fee handler
type GetFeeHandlerFunc func(GetFeeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFeeHandlerFunc) Handle(params GetFeeParams) middleware.Responder {
	return fn(params)
}

// GetFeeHandler interface for that can handle valid get fee params
type GetFeeHandler interface {
	Handle(GetFeeParams) middleware.Responder
}

// NewGetFee creates a new http.Handler for the get fee operation
func NewGetFee(ctx *middleware.Context, handler GetFeeHandler) *GetFee {
	return &GetFee{Context: ctx, Handler: handler}
}

/* GetFee swagger:route GET /fee getFee

list all fees in whole FIO as a float

*/
type GetFee struct {
	Context *middleware.Context
	Handler GetFeeHandler
}

func (o *GetFee) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFeeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
