// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFeeVotesFeevoteProducerHandlerFunc turns a function with the right signature into a get fee votes feevote producer handler
type GetFeeVotesFeevoteProducerHandlerFunc func(GetFeeVotesFeevoteProducerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFeeVotesFeevoteProducerHandlerFunc) Handle(params GetFeeVotesFeevoteProducerParams) middleware.Responder {
	return fn(params)
}

// GetFeeVotesFeevoteProducerHandler interface for that can handle valid get fee votes feevote producer params
type GetFeeVotesFeevoteProducerHandler interface {
	Handle(GetFeeVotesFeevoteProducerParams) middleware.Responder
}

// NewGetFeeVotesFeevoteProducer creates a new http.Handler for the get fee votes feevote producer operation
func NewGetFeeVotesFeevoteProducer(ctx *middleware.Context, handler GetFeeVotesFeevoteProducerHandler) *GetFeeVotesFeevoteProducer {
	return &GetFeeVotesFeevoteProducer{Context: ctx, Handler: handler}
}

/* GetFeeVotesFeevoteProducer swagger:route GET /fee/votes/feevote/{producer} getFeeVotesFeevoteProducer

list a producer's fee votes

*/
type GetFeeVotesFeevoteProducer struct {
	Context *middleware.Context
	Handler GetFeeVotesFeevoteProducerHandler
}

func (o *GetFeeVotesFeevoteProducer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFeeVotesFeevoteProducerParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
