// Code generated by go-swagger; DO NOT EDIT.

// Package restapi fio-fee-reporter
//
//  Provides information about FIO fees
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /v1
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
